services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    restart: always
    env_file:
      - .env
    depends_on:
      - wordpress
  wordpress:
    container_name: wordpress-php
    build: ./requirements/wordpress/.
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    restart: always
    env_file:
      - .env
    depends_on:
      - mariadb
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network
    restart: always
    env_file:
      - .env

volumes:
  mariadb_data:
    driver: local
    driver_opts: 
      type: none
      device: /home/kmiyazaw/data/database
      #device: ./database
      o: bind
  wordpress_data:
    driver: local
    driver_opts: 
      type: none
      device: /home/kmiyazaw/data/web
      #device: ./web
      o: bind

networks:
  inception_network:
    driver: bridge