CREATE DATABASE IF NOT EXISTS `${MARIADB_DB_NAME}`;
CREATE USER IF NOT EXISTS '${MARIADB_USER}'@'%' IDENTIFIED BY '${MARIADB_PASSWORD}';
GRANT ALL PRIVILEGES ON `${MARIADB_DB_NAME}`.* TO '${MARIADB_USER}'@'%';
FLUSH PRIVILEGES;
